import Head from 'next/head'
import MovieDisplay from '../components/MovieDisplay';
import styles from '../styles/Home.module.css'
import { IMovieItens } from '../types/types';
import {API_KEY} from '../utils/api';

interface Props {
  results: Array<IMovieItens>;
}

const Home = ({ results }:Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Movies TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}><a href="">Next Movies TS</a></h1>

        <p className={styles.description}>
          Mais Populares da semana:{' '}
        </p>

        <div className={styles.grid}>
          {results?.map((movie) => (
            <div className={styles.card} key={movie.id}>
              <MovieDisplay
                imgURL={`https://image.tmdb.org/t/p/w500${movie.poster_path}`}
                title={movie.name  ?? movie.original_title ?? movie.title ?? movie.original_name}
                release_date={movie.release_date ?? movie.first_air_date}
                vote_average={movie.vote_average}
              />
            </div>))}
        </div>
      </main>
    </div>
  )
}

export default Home;


export async function getStaticProps() {
  console.log(API_KEY)
  const res = await fetch('http://localhost:3000/api/tmdb/weked');
  const data = await res.json();
  return {
    props: {
      results: data.results
    }
  }
}