import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface Props {
  results: Array<{
    id: number;
    title: string;
    original_language: string;
    poster_path: string;
    release_date: string;
    vote_average: number;
    media_type: string;
    backdrop_path: string;
    genre_ids: Array<number>;
    overview: string;
}>;
}

const Home = ({ results }:Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Movies TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Mais Populares da semana:{' '}
        </p>

        <div className={styles.grid}>
          {results?.map((movie) => (<li key={movie.id}>
            <img src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`} alt={movie.title} width={200} height={300} />
            <h3>Titulo: {movie.title}</h3>
            <p>Lançamento: {movie.release_date}</p>
            <p>Nota do publico: {movie.vote_average}</p>
          </li>))}
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;


export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/tmdb/weked');
  const data = await res.json();
  return {
    props: {
      results: data.results
    }
  }
}